project:
  type: website
  output-dir: docs

website:
  title: "Stat 320: Biostatistics"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - data.qmd

format:
  html:
    theme: [flatly, theme.scss]
    css: styles.css
    toc: true
    axe: true
    highlight-style: a11y
